name: local_assets_server
description: HTTP Server which serves local assets
version: 1.0.2+5
author: Andrei Lesnitsky <andrei.lesnitsky@gmail.com>
homepage: https://github.com/lesnitsky/flutter_local_assets_server

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.6.2
  mime: ^0.9.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
