name: local_assets_server
description: HTTP Server which serves local assets
version: 2.0.2+11
homepage: https://github.com/lesnitsky/local_assets_server

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mime: ^1.0.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
